---
  - name: Install docker and run sonarqube container
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Run the equivalent of "apt-get update" as a separate step
        apt:
          update_cache: yes

      - name: download docker-ce-cli
        get_url:
          url: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_20.10.2~3-0~ubuntu-bionic_amd64.deb
          dest: /root/docker-ce-cli_20.10.2~3-0~ubuntu-bionic_amd64.deb
          mode: 0640
      - name: Install docker-ce-cli package
        apt:
          deb: /root/docker-ce-cli_20.10.2~3-0~ubuntu-bionic_amd64.deb
      - name: download containerd
        get_url:
          url: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.4.3-1_amd64.deb
          dest: /root/containerd.io_1.4.3-1_amd64.deb
          mode: 0640
      - name: Install containerd package
        apt:
          deb: /root/containerd.io_1.4.3-1_amd64.deb
      - name: download docker-ce
        get_url:
          url: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_20.10.2~3-0~ubuntu-bionic_amd64.deb
          dest: /root/docker-ce_20.10.2~3-0~ubuntu-bionic_amd64.deb
          mode: 0640
      - name: Install docker-ce package
        apt:
          deb: /root/docker-ce_20.10.2~3-0~ubuntu-bionic_amd64.deb

      - name: Install python3-pip
        package:
          name: python3-pip
          state: present

      - name: pip install docker
        pip:
          name: docker

      - name: Set vm.max_map_count
        command: sysctl -w vm.max_map_count=262144

      - name: Set fs.file-max
        command: sysctl -w fs.file-max=65536

      - name: Set nofile for vagrant user
        pam_limits:
          domain: vagrant
          limit_type: '-'
          limit_item: nofile
          value: '65536'
        notify:
        - Reboot

      - name: Set nproc for vagrant user
        pam_limits:
          domain: vagrant
          limit_type: '-'
          limit_item: nproc
          value: '4096'
        notify:
        - Reboot

      - name: Container present
        community.docker.docker_container:
          name: sonarqube
          state: started
          ports:
            - "9000:9000"
          image: sonarqube:8.6.0-community
          volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions 
            - sonarqube_logs:/opt/sonarqube/logs

    handlers:
      - name: Reboot
        reboot:
